version: '3'
services:
  app:
    container_name: spring-redis
    build: .
    ports:
    - 8088:8088
    links:
    - redis
  redis:
    container_name: redis
    image: redis
    hostname: redis
    ports:
    - 6379:6379